<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Carbon\Carbon;


class PegawaiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('pegawai')->insert([
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Sri Christyani, S.Pd.M.Pd',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => new Carbon('1964-03-10'),
                'nip_lama' => '131 910 550',
                'nip_baru' => '19641107 199003 2 011',
                'tmt_golongan' => new Carbon('2015-04-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Pend Eko Kons Adminis perk/A.IV',
                'tahun_lulus' => '2002',
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 3,
                'golongan_id' => 6,
                'jabatan_id' => 2,
                'agama_id' => 1,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Greytie J Wongkaren, S.Pd',
                'tempat_lahir' => 'Manado',
                'tanggal_lahir' => new Carbon('1981-08-18'),
                'nip_lama' => '640 051 773',
                'nip_baru' => '19810818 200801 2 027',
                'tmt_golongan' => new Carbon('2023-10-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Bahasa Jepang/A.IV',
                'tahun_lulus' => '2005',
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 3,
                'golongan_id' => 12,
                'jabatan_id' => 12,
                'agama_id' => 3,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Merry Losba, SE',
                'tempat_lahir' => 'Abepura',
                'tanggal_lahir' => new Carbon('1980-05-07'),
                'nip_lama' => '640 048 579',
                'nip_baru' => '19800507 200701 2 017',
                'tmt_golongan' => new Carbon('2022-10-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Ekonomi Manajemen/A.IV',
                'tahun_lulus' => '2007',
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 3,
                'golongan_id' => 14,
                'jabatan_id' => 11,
                'agama_id' => 2,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Saferiana Boseke, S.Pd',
                'tempat_lahir' => 'Woloam Tiga',
                'tanggal_lahir' => new Carbon('1973-04-04'),
                'nip_lama' => '132 265 048',
                'nip_baru' => '19730404 200008 2 001',
                'tmt_golongan' => new Carbon('2016-01-10'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Pendidikan PPKN',
                'tahun_lulus' => '1997',
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 3,
                'golongan_id' => 14,
                'jabatan_id' => 7,
                'agama_id' => 3,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Setia Suci Mulyati, SE,MM',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => new Carbon('1968-08-15'),
                'nip_lama' => null,
                'nip_baru' => '19690815 199412 2 002',
                'tmt_golongan' => new Carbon('2017-04-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Ekonomi',
                'tahun_lulus' => null,
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 3,
                'golongan_id' => 14,
                'jabatan_id' => 4,
                'agama_id' => 1,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Elyzabeth Dwi Victoria Demetouw, S.Th',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => new Carbon('1984-01-08'),
                'nip_lama' => null,
                'nip_baru' => '19840108 201004 2 002',
                'tmt_golongan' => new Carbon('2022-01-04'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Pendidikan Agama Kristen',
                'tahun_lulus' => null,
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 1,
                'golongan_id' => 12,
                'jabatan_id' => 17,
                'agama_id' => 3,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Alberth Gunawan, S.Pd',
                'tempat_lahir' => 'Jayapura',
                'tanggal_lahir' => new Carbon('1984-01-09'),
                'nip_lama' => null,
                'nip_baru' => '19840109 200909 1 002',
                'tmt_golongan' => new Carbon('2022-01-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Magister Manajemen',
                'tahun_lulus' => null,
                'pendidikan_terakhir_id' => 10,
                'keturunan_id' => 3,
                'golongan_id' => 11,
                'jabatan_id' => 4,
                'agama_id' => 3,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Selfie',
                'tempat_lahir' => 'Bitung',
                'tanggal_lahir' => new Carbon('1968-09-22'),
                'nip_lama' => null,
                'nip_baru' => '19680922 201505 2 001',
                'tmt_golongan' => new Carbon('2023-01-10'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Perdagangan',
                'tahun_lulus' => '1991',
                'pendidikan_terakhir_id' => 3,
                'keturunan_id' => 3,
                'golongan_id' => 7,
                'jabatan_id' => 19,
                'agama_id' => 1,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'James Matheos Salaki',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => new Carbon('1967-06-23'),
                'nip_lama' => null,
                'nip_baru' => '19670623 201506 1 001',
                'tmt_golongan' => new Carbon('2023-01-10'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'IPA',
                'tahun_lulus' => '1987',
                'pendidikan_terakhir_id' => 2,
                'keturunan_id' => 3,
                'golongan_id' => 9,
                'jabatan_id' => 19,
                'agama_id' => 3,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Tyas Waluyo, S.Pd.I',
                'tempat_lahir' => 'Grobogan',
                'tanggal_lahir' => new Carbon('1983-12-07'),
                'nip_lama' => null,
                'nip_baru' => '19831207 201506 1 001',
                'tmt_golongan' => new Carbon('2019-10-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Pendidikan Islam',
                'tahun_lulus' => '2002',
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 3,
                'golongan_id' => 9,
                'jabatan_id' => 16,
                'agama_id' => 1,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Daryunah, S.Ag',
                'tempat_lahir' => 'Karang Anyar',
                'tanggal_lahir' => new Carbon('1968-06-29'),
                'nip_lama' => null,
                'nip_baru' => '19680629 201505 2 001',
                'tmt_golongan' => new Carbon('2021-10-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Pend.Agama Islam',
                'tahun_lulus' => '1998',
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 3,
                'golongan_id' => 11,
                'jabatan_id' => 16,
                'agama_id' => 1,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Hana Bunga, S.IP',
                'tempat_lahir' => 'Lempo Poton',
                'tanggal_lahir' => new Carbon('1965-10-02'),
                'nip_lama' => '131 911 623',
                'nip_baru' => '19651002 199003 2 011',
                'tmt_golongan' => new Carbon('2006-10-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Ilmu Politik',
                'tahun_lulus' => '2011',
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 3,
                'golongan_id' => 13,
                'jabatan_id' => 1,
                'agama_id' => 3,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Drs. Sutoto, M.T',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => new Carbon('1966-04-03'),
                'nip_lama' => '131 949 336',
                'nip_baru' => '19660903 199103 1 006',
                'tmt_golongan' => new Carbon('2005-10-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Bidang Teknik/A.IV',
                'tahun_lulus' => '2004',
                'pendidikan_terakhir_id' => 10,
                'keturunan_id' => 3,
                'golongan_id' => 13,
                'jabatan_id' => 5,
                'agama_id' => 1,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Joelliarti, S.IP',
                'tempat_lahir' => 'Mojokerto',
                'tanggal_lahir' => new Carbon('1964-07-14'),
                'nip_lama' => '131 961 637',
                'nip_baru' => '19640714 199103 2 010',
                'tmt_golongan' => new Carbon('2007-04-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Ilmu Politik',
                'tahun_lulus' => '2011',
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 3,
                'golongan_id' => 13,
                'jabatan_id' => 1,
                'agama_id' => 1,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Risma Sibarani, SE,MM',
                'tempat_lahir' => 'Ujung Tanduk',
                'tanggal_lahir' => new Carbon('1976-08-14'),
                'nip_lama' => '640 045 461',
                'nip_baru' => '19760814 200605 2 001',
                'tmt_golongan' => new Carbon('2018-10-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => null,
                'tahun_lulus' => '2010',
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 3,
                'golongan_id' => 12,
                'jabatan_id' => 1,
                'agama_id' => 3,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Dra. Sri Sunarti',
                'tempat_lahir' => 'Purworejo',
                'tanggal_lahir' => new Carbon('1968-01-17'),
                'nip_lama' => '132 136 156',
                'nip_baru' => '19680117 199512 2 005',
                'tmt_golongan' => new Carbon('2008-10-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Adm Pem.Umum/A.IV',
                'tahun_lulus' => '1992',
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 3,
                'golongan_id' => 13,
                'jabatan_id' => 1,
                'agama_id' => 1,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Elisabeth ArungRuba, S.KM, M.Pd',
                'tempat_lahir' => 'Manokwari',
                'tanggal_lahir' => new Carbon('1972-04-08'),
                'nip_lama' => '132 150 293',
                'nip_baru' => '19720408 199603 2 002',
                'tmt_golongan' => new Carbon('2013-10-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Pendidikan',
                'tahun_lulus' => '2022',
                'pendidikan_terakhir_id' => 10,
                'keturunan_id' => 3,
                'golongan_id' => 13,
                'jabatan_id' => 3,
                'agama_id' => 3,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Dina Widi N, S.Pd',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => new Carbon('1969-09-06'),
                'nip_lama' => '132 172 803',
                'nip_baru' => '19690906 199703 2 001',
                'tmt_golongan' => new Carbon('2023-10-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Pendidikan Sejarah/A.IV',
                'tahun_lulus' => '1995',
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 3,
                'golongan_id' => 14,
                'jabatan_id' => 6,
                'agama_id' => 1,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Sukardi, S.Pd',
                'tempat_lahir' => 'Dukuh Seti',
                'tanggal_lahir' => new Carbon('1971-10-03'),
                'nip_lama' => '132 203 652',
                'nip_baru' => '19711003 199802 1 003',
                'tmt_golongan' => new Carbon('2021-10-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Pendidikan Bahasa Inggris/A.IV',
                'tahun_lulus' => '2005',
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 3,
                'golongan_id' => 14,
                'jabatan_id' => 3,
                'agama_id' => 1,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Elia Waromi, S.Pd.M.Pd',
                'tempat_lahir' => 'Serui',
                'tanggal_lahir' => new Carbon('1974-07-13'),
                'nip_lama' => '132 203 647',
                'nip_baru' => '19740713 199802 1 001',
                'tmt_golongan' => new Carbon('2022-10-01'),
                'tmt_jabatan' => '2012-01-25',
                'kepala_sekolah' => true,
                'jurusan' => 'Pendidikan Bahasa Inggris/A.IV',
                'tahun_lulus' => '2014',
                'pendidikan_terakhir_id' => 10,
                'keturunan_id' => 1,
                'golongan_id' => 15,
                'jabatan_id' => 3,
                'agama_id' => 3,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Umi Rodliyah, SE.M.Si',
                'tempat_lahir' => 'Ponorog',
                'tanggal_lahir' => new Carbon('1977-03-11'),
                'nip_lama' => null,
                'nip_baru' => '19770311 201004 2 001',
                'tmt_golongan' => new Carbon('2023-10-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Magister Ekonomi /A.IV',
                'tahun_lulus' => '2014',
                'pendidikan_terakhir_id' => 10,
                'keturunan_id' => 3,
                'golongan_id' => 12,
                'jabatan_id' => 18,
                'agama_id' => 1,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Hasdetati',
                'tempat_lahir' => 'Managalu',
                'tanggal_lahir' => new Carbon('1967-12-03'),
                'nip_lama' => '131 630 426',
                'nip_baru' => '19661203 198603 2 007',
                'tmt_golongan' => new Carbon('2022-01-10'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Paket C',
                'tahun_lulus' => '2006',
                'pendidikan_terakhir_id' => 2,
                'keturunan_id' => 3,
                'golongan_id' => 10,
                'jabatan_id' => 19,
                'agama_id' => 3,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Marthince Ronsumbre, S.Pd',
                'tempat_lahir' => 'Tiom',
                'tanggal_lahir' => new Carbon('1981-05-10'),
                'nip_lama' => null,
                'nip_baru' => '19810510 200605 2 001',
                'tmt_golongan' => new Carbon('2021-01-10'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Matematika/ A.IV',
                'tahun_lulus' => null,
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 1,
                'golongan_id' => 13,
                'jabatan_id' => 10,
                'agama_id' => 3,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Zalaita Trikurniawati, S.Pd',
                'tempat_lahir' => 'Rojipolo',
                'tanggal_lahir' => new Carbon('1976-07-14'),
                'nip_lama' => '640 035 057',
                'nip_baru' => '19760714 200501 2 018',
                'tmt_golongan' => new Carbon('2021-10-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Pend.MIPA Matematika/A.IV',
                'tahun_lulus' => '2000',
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 3,
                'golongan_id' => 13,
                'jabatan_id' => 10,
                'agama_id' => 1,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Fajiri Audu, S.Pd',
                'tempat_lahir' => 'Makian',
                'tanggal_lahir' => new Carbon('1979-05-20'),
                'nip_lama' => null,
                'nip_baru' => '19792005 200909 1 003',
                'tmt_golongan' => new Carbon('2020-10-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'PenJasKes/A.IV',
                'tahun_lulus' => '2003',
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 3,
                'golongan_id' => 11,
                'jabatan_id' => 14,
                'agama_id' => 1,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Katmiatun',
                'tempat_lahir' => 'Blitar',
                'tanggal_lahir' => new Carbon('1973-10-14'),
                'nip_lama' => null,
                'nip_baru' => '19731014 201506 2 001',
                'tmt_golongan' => new Carbon('2023-01-10'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Koperasi',
                'tahun_lulus' => '1992',
                'pendidikan_terakhir_id' => 3,
                'keturunan_id' => 3,
                'golongan_id' => 7,
                'jabatan_id' => 19,
                'agama_id' => 1,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Delima Tamba, S.Pd',
                'tempat_lahir' => 'Hanna',
                'tanggal_lahir' => new Carbon('1971-10-23'),
                'nip_lama' => '640 045 431',
                'nip_baru' => '19711023 200605 2 002',
                'tmt_golongan' => new Carbon('2023-10-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Pend.Akuntansi/A.IV',
                'tahun_lulus' => '2006',
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 3,
                'golongan_id' => 14,
                'jabatan_id' => 2,
                'agama_id' => 3,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Urai, SH',
                'tempat_lahir' => 'Seriti',
                'tanggal_lahir' => new Carbon('1972-12-08'),
                'nip_lama' => '132 095 784',
                'nip_baru' => '19721208 199403 1 002',
                'tmt_golongan' => new Carbon('2017-10-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Hukum',
                'tahun_lulus' => '2003',
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 3,
                'golongan_id' => 12,
                'jabatan_id' => 19,
                'agama_id' => 3,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Sitti Aisa, A.Md.Kom',
                'tempat_lahir' => 'Abepura',
                'tanggal_lahir' => new Carbon('1976-01-27'),
                'nip_lama' => '640 048 483',
                'nip_baru' => '19760127 200701 2 008',
                'tmt_golongan' => new Carbon('2023-01-10'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Teknik Informatika',
                'tahun_lulus' => '1999',
                'pendidikan_terakhir_id' => 7,
                'keturunan_id' => 3,
                'golongan_id' => 11,
                'jabatan_id' => 19,
                'agama_id' => 1,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Hilda Heryanti, SE,M.M',
                'tempat_lahir' => 'Jayapura',
                'tanggal_lahir' => new Carbon('1976-09-06'),
                'nip_lama' => '640 038 582',
                'nip_baru' => '19760906 200501 2 012',
                'tmt_golongan' => new Carbon('2021-10-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Manajemen',
                'tahun_lulus' => null,
                'pendidikan_terakhir_id' => 10,
                'keturunan_id' => 3,
                'golongan_id' => 14,
                'jabatan_id' => 2,
                'agama_id' => 1,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Dece Silviana Kondomo, S.Pd',
                'tempat_lahir' => 'Serui',
                'tanggal_lahir' => new Carbon('1981-09-06'),
                'nip_lama' => null,
                'nip_baru' => '19810906 201004 2 001',
                'tmt_golongan' => new Carbon('2021-01-10'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Bimbingan & Konseling/A.IV',
                'tahun_lulus' => null,
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 1,
                'golongan_id' => 11,
                'jabatan_id' => 13,
                'agama_id' => 3,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'James Gultom, S.Pd',
                'tempat_lahir' => 'Amborgang',
                'tanggal_lahir' => new Carbon('1977-10-28'),
                'nip_lama' => null,
                'nip_baru' => '19772010 200909 1 001',
                'tmt_golongan' => new Carbon('2020-10-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Ekonomi/A.IV',
                'tahun_lulus' => '2004',
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 3,
                'golongan_id' => 12,
                'jabatan_id' => 5,
                'agama_id' => 2,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Riskyfitri Purbyansari, S.Pd, M.Pd',
                'tempat_lahir' => 'Nabira',
                'tanggal_lahir' => new Carbon('1972-11-04'),
                'nip_lama' => '132 216 182',
                'nip_baru' => '19721104 199803 2 011',
                'tmt_golongan' => new Carbon('2022-10-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Pend Bahasa Indonesia/A.IV',
                'tahun_lulus' => '2011',
                'pendidikan_terakhir_id' => 10,
                'keturunan_id' => 3,
                'golongan_id' => 15,
                'jabatan_id' => 8,
                'agama_id' => 1,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Michel Richard Bukorpioper',
                'tempat_lahir' => 'Jayapura',
                'tanggal_lahir' => new Carbon('1972-05-15'),
                'nip_lama' => '132 225 057',
                'nip_baru' => '19720515 199903 1 012',
                'tmt_golongan' => new Carbon('2008-04-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Bahasa Inggris',
                'tahun_lulus' => '1997',
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 1,
                'golongan_id' => 13,
                'jabatan_id' => 9,
                'agama_id' => 3,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Marselinus Kepata, S.Ag, M.Hum',
                'tempat_lahir' => 'Atawolo',
                'tanggal_lahir' => new Carbon('1975-12-28'),
                'nip_lama' => null,
                'nip_baru' => '19751228 201004 1 002',
                'tmt_golongan' => new Carbon('2021-01-10'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Filsafat Agama/A.IV',
                'tahun_lulus' => '2004',
                'pendidikan_terakhir_id' => 10,
                'keturunan_id' => 3,
                'golongan_id' => 12,
                'jabatan_id' => 15,
                'agama_id' => 2,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Yuliana Wulandari, S.pd',
                'tempat_lahir' => 'Wamena',
                'tanggal_lahir' => new Carbon('1975-03-04'),
                'nip_lama' => '132 225 672',
                'nip_baru' => '19750304 199903 2 006',
                'tmt_golongan' => new Carbon('2019-10-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Pend.Bahasa Inggris/A.IV',
                'tahun_lulus' => '1998',
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 3,
                'golongan_id' => 14,
                'jabatan_id' => 9,
                'agama_id' => 1,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Wahyuni Tri Hastuti, SE',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => new Carbon('1976-06-16'),
                'nip_lama' => '640 032 323',
                'nip_baru' => '19760616 200312 2 021',
                'tmt_golongan' => new Carbon('2023-10-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Ekonomi Akuntansi/A.IV',
                'tahun_lulus' => '2001',
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 3,
                'golongan_id' => 14,
                'jabatan_id' => 2,
                'agama_id' => 1,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Kornelia Kawaitouw, S.Sos,MM',
                'tempat_lahir' => 'Jayapura',
                'tanggal_lahir' => new Carbon('1981-09-18'),
                'nip_lama' => null,
                'nip_baru' => '19810918 201505 2 001',
                'tmt_golongan' => new Carbon('2023-01-10'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Manajemen',
                'tahun_lulus' => '2004',
                'pendidikan_terakhir_id' => 10,
                'keturunan_id' => 1,
                'golongan_id' => 11,
                'jabatan_id' => 19,
                'agama_id' => 3,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Rina Sulistiani, S.Pd',
                'tempat_lahir' => 'Magetan',
                'tanggal_lahir' => new Carbon('1981-03-21'),
                'nip_lama' => '640 039 686',
                'nip_baru' => '19810321 200605 2 001',
                'tmt_golongan' => new Carbon('2019-10-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Pend. Bahasa Inggris/A.IV',
                'tahun_lulus' => '2006',
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 3,
                'golongan_id' => 13,
                'jabatan_id' => 9,
                'agama_id' => 1,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Paulus Warmetan, S.Pd',
                'tempat_lahir' => 'Mantembu',
                'tanggal_lahir' => new Carbon('1985-09-12'),
                'nip_lama' => null,
                'nip_baru' => '19850912 201004 1 002',
                'tmt_golongan' => new Carbon('2021-04-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'PenJasKes/A.IV',
                'tahun_lulus' => '2009',
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 1,
                'golongan_id' => 11,
                'jabatan_id' => 14,
                'agama_id' => 3,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Leonard Christian Toisuta, S.Pd',
                'tempat_lahir' => 'Leinitu',
                'tanggal_lahir' => new Carbon('1975-12-21'),
                'nip_lama' => '640 043 912',
                'nip_baru' => '19751221 200605 1 001',
                'tmt_golongan' => new Carbon('2014-04-01'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Pend. Sejarah/A.IV',
                'tahun_lulus' => '2004',
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 3,
                'golongan_id' => 12,
                'jabatan_id' => 6,
                'agama_id' => 3,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ],
            [
                'id_uuid' => Str::uuid(),
                'nama' => 'Rini Rokhmawati, S.Pd',
                'tempat_lahir' => 'Tegal',
                'tanggal_lahir' => new Carbon('1979-02-19'),
                'nip_lama' => null,
                'nip_baru' => '19791902 200909 2 001',
                'tmt_golongan' => new Carbon('2021-01-10'),
                'tmt_jabatan' => null,
                'kepala_sekolah' => false,
                'jurusan' => 'Pend. Matematika/A.IV',
                'tahun_lulus' => null,
                'pendidikan_terakhir_id' => 9,
                'keturunan_id' => 3,
                'golongan_id' => 12,
                'jabatan_id' => 10,
                'agama_id' => 3,
                'created_at' => date('Y-m-d h:i:s'),
                'updated_at' => date('Y-m-d h:i:s'),
            ]
        ]);
    }
}
