# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    tags:
      - v**

jobs:
  run-migration:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' && contains(github.ref_name, 'migration')
    steps:
      - name: Staging Stage - Deploy via SSH
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/simpeg-be/
            composer run-script startup-project
  run:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' && contains(github.ref_name, 'staging')
    steps:
      - name: Staging Stage - Deploy via SSH
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/simpeg-be/
            git pull origin master

    